### ISSUE TITLE
Data not loading

### ISSUE THREAD

**Issue by Zitchas** [robot-rover/endless-sky-viewer#5]
## Description of problem
When I start the viewer, it gets stuck at about 90% loading point.

## What is expected
That it eventually loads all the data and proceeds to display the viewer

## Solutions attempted
1. Pointing it at a standard steam installation (0.9.12)
2. Pointing it at a GitHub Desktop managed continuous installation.
3. Pointing it at a standard steam install with all the data files unpacked out of their folders, so that the data folder just has a ton of files instead of any folders.

**Comment by robot-rover** [comment]
I'm pretty sure this was due to the game adding new outfit attributes which weren't accounted for yet. I just pushed a couple of commits. I'll be doing a new release soon.

**Comment by Zitchas** [comment]
Great! I definitely enjoyed using it back when I could get it to work. I find it much more convenient than installing an all-content plug-in or messing around with outfitters. Looking forward to having it working again.

On the plus side, once all the new attributes and effects, there probably won't be many more coming in the future - Amazinite made a point of adding almost all the different combinations of various effects, resistances, protections, and the like that he could think of, just to get it all done all at once. Which means fewer code changes in the future.

**Comment by robot-rover** [comment]
Try out this new release and let me know if it works, otherwise get in touch with me so we can try to debug it:
[https://github.com/robot-rover/endless-sky-viewer/releases/tag/0.0.4](https://github.com/robot-rover/endless-sky-viewer/releases/tag/0.0.4)

**Comment by Zitchas** [comment]
OK, good news and bad news.

Bad news first: It still won't load from my GitHub repository (this is my primary gaming install since I spend most of my time playing/testing PRs)

Good news, it *does* load the data successfully from the steam beta 0.9.13 install! So that's a massive improvement. Currently poking around in it, and stuff seems to work (and the movement related attributes seem to be grouped together as per my other request), so looking good.

edit: Clarified that the first test was using my Github Repository as the source location. This isn't a install via the GitHub installer/zip, but rather the full git-managed repository.

Admitedly there is a lot of extra stuff in there that might be confusing the Viewer, but my bet would be on the extra folders. Would it be possible to have it ignore any folder starting with a period? Or alternatively, specifically blacklist:

- .git
- .github

(Those two folders, on my side, have roughly 7000 files in 300+ folders, encompassing almost half a GB in data. Presumably including all my various branches and commit histories and stuff like that)

It is entirely possible that the other extra files are causing problems too, but those two git files seems the most likely, since they actually contain alternate copies of the Endless Sky data - although I'm not sure if it is in a form that the Viewer can parse. If you do implement the folder blacklist, including the other non-relevant ones too might be a good idea. bin, build, EndlessSky.xcodeproj, lib, obj, source, tests, utils, and XCode are all more or less irrelevant for the purposes of viewing ships.

Steam folder on the left, Github repository on the right
![Steam vs GitHub Repository](https://user-images.githubusercontent.com/32169904/120071430-a7313700-c04c-11eb-9fe7-b65f52f309e4.png)

**Comment by robot-rover** [comment]
That shouldn't break it, I'm thinking there's some wierd data ion your git repo that I'm not accounting for. Are you on the endless sky discord and what is your discord handle?
Edit: actually, just add me `robot_rover#4437`

**Comment by Zitchas** [comment]
Yes, and the same name as here: Zitchas.

**Comment by Zitchas** [comment]
I just made a copy of my github folder, and I'm deleting things one by one and getting the Viewer to reload it after each time to see if I can figure out which thing it is getting hung up on.

**Comment by robot-rover** [comment]
For posterity, this issue was caused by a file that had windows line endings rather than unix. I'm fairly sure that the game also expects unix line endings so I think I am going to leave this parser the same as the one in the game.

**Comment by Zitchas** [comment]
One further note: The game actually handles having windows file endings just fine (I ran Endless Sky with those same files without problems for over a year), but yes, better to have things the way they are intended to be. I suspect the windows file ending support is probably included to facilitate development and plug-ins, both of which are often made by people with less technical knowledge.

**Comment by robot-rover** [comment]
Hmm apparently you are right, I thought the game didn't support CRLF endings but I guess it added support for them since I translated the parser to java. I've found where the change was and added support in ca6c5d9
